// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyacutmyzxnwedyjqiom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5YWN1dG15enhud2VkeWpxaW9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MzA4NDQsImV4cCI6MjA2NjMwNjg0NH0.JDT-plqPyv2U_qitsMdQBfn-etdl13Tw7FjEq8PW_Kg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);